### PR TITLE
replace .success() with .done() due to JS deprecation. Fixes UI dash load error.

### PR DESCRIPTION
**Pull request by akh13**
Apologies for the duplicate PR. This seems to fix a dashboard load error that prevents the javascript from running properly. Without it, I receive this in the console:

Uncaught TypeError: loader.load(...).success is not a function
    loadNextJob https://rundeck.testsite.com/plugin/file/UI/ui-job-graph/js/jobgraph.js:755
    loadJobListData https://rundeck.testsite.com/plugin/file/UI/ui-job-graph/js/jobgraph.js:763
    loadJobsListPage https://rundeck.testsite.com/plugin/file/UI/ui-job-graph/js/jobgraph.js:459

To fix this, the method has to be changed as below, because there is .success() in these locations. Can someone please verify if this fix works?

### CODE REVIEW

**Comment by benbugohit** [comment]
thanks ! it works on 4.11

**Comment by snyrkill** [comment]
Thank you. This now works in 4.9, 4.10 and 4.11 :)
This also fixes the ui-job-list plugin.

**Comment by ptrybowski** [comment]
Are there plans to merge this PR? Is the plugin even supported at this point?
